# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConvertCurrency' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConvertCurrency
  pod 'Alamofire'
  target 'ConvertCurrencyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConvertCurrencyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
